### PR TITLE
Swift 4 support

### PR DESCRIPTION
**Pull request by MojtabaHs**
Swift 4 support without deprecating swift 3 support.
Clean code according to swift-style-guide from Apple, Raywenderlich, Swift lint, WWDC, etc.

### CODE REVIEW

**Comment by frenetisch-applaudierend** [comment]
Hi MojtabaHS

Wow, that's thorough work, thanks for the contributions. A few questions and comments:

* If I see this correctly you changes include PRs #3 and #4, right?

* I would be glad if you could remove the following commits from the PR:
  - [4057d57] Uses of Self: I'm aware that the public opinion on this is mostly different, but I really like the explicit self, since it helps me tremendously when viewing code without syntax highlighting (e.g. in PRs)
  - [f772d99] Extra vertical whitespaces removed: Again, this is personal preference but it helps me visually scanning the file

If you could address those, I'm ready to merge, quick test and push a new version on cocoapods.

**Comment by MojtabaHs** [comment]
Hi @frenetisch-applaudierend 

"@objc" keyword added like those PRs you mentioned, but since you want swift 3 support (that apple deprecated it, but you mentioned it in PR #3 ), I managed it deferent a bit. So now it's supports both.

And about the styles, I used world wide references about swift-style-guide and clean your handy "Open source" framework the way that community agreed to. I'm highly recommending you to keep it . But if you want those "self"s and "vertical space"s back, please let me know. It wouldn't take me much time ;)

**Comment by frenetisch-applaudierend** [comment]
Swift 3 support is not really a _must_, I think you misunderstood my comment in #3. So if it makes it easier we can also drop it. It feels a bit weird to create a new major version for this, but that's inevitable anyway.

As for the code style: I'm very aware that I'm deviating here from the "official" norm, but for my own projects I do this deliberately in those few parts. So yes, please give my "self"s and "\n"s back ;-). Just to be clear, that's not a criticism on you or anything; I'm really thankful for the contribution!

**Comment by MojtabaHs** [comment]
Hey @frenetisch-applaudierend 
I forgot to say you can instantly recognize "self" related variables by setting your preferred custom color in Xcode -> Preferences -> Fonts & Colors -> **Project Instance Variables and Globals** and not crossing the "Official" norm ;)

**Comment by frenetisch-applaudierend** [comment]
I see, I found someone who has as strong an opinion on this topic as I do 😄 

True in Xcode this is generally no problem. But I frequently have to review PRs which most often do not have proper syntax highlighting for swift and don't show the whole context. This makes it very hard to be sure if that variable you're seeing is local or class scoped. Especially since swift allows shadowing variables. Therefore I developed the habit of always prefixing class member accesses with `self`.

**Pull request merged**
