### PR TITLE
added SPM support

### PR DESCRIPTION
**Pull request by freemansion**

### CODE REVIEW

**Comment by frenetisch-applaudierend** [comment]
Hi Stanislau

Thank you for your contribution!

Looking at the files I see a test case which looks autogenerated to me. As such I would appreciate it if you can remove this part from the PR and I'll be happy to merge.

Cheers,
Markus

**Comment by freemansion** [comment]
Hi Markus,

Yep, you're right, the test cases are autogenerated and has been added by default with `swift package init`
I've removed them from this PR.

Kind regards,
Stan

**Comment by frenetisch-applaudierend** [comment]
Great, thanks!

Is there anything else I need to do, to make it available for SPM after merging? Please excuse my question, I didn't look too much at SPM yet 😄

**Comment by freemansion** [comment]
I think the only thing you have to do after the merge, is to update git tag and push it to the repo, so the Xcode will be able to find it.

Below is the screenshot with example:
Screen Shot 2020-11-09 at 16 51 13

Kind regards,
Stan

**Comment by frenetisch-applaudierend** [comment]
Done! Let me know if there are any problems.

Thanks again for your efforts!

**Comment by freemansion** [comment]
Everything works fine!
Thanks for the library, btw!

**Pull request merged**
