### PR TITLE
Support Swift 4.2 & CI environment

### PR DESCRIPTION
**Pull request by giginet**
Hi! We are using this project via CocoaPods.
However, a Xcode migration tool is failed because of this project.

So, I updated Swift version to 4.2.
And in this time, I introduced CI environment.

### CODE REVIEW

**Comment by frenetisch-applaudierend** [comment]
Hi giginet,

Thank you so much for your contribution. I'm a little absorbed right now so please allow me a few days to review/merge/update. I try to get on it this weekend!

Cheers, Markus

**Comment by giginet** [comment]
Hi @frenetisch-applaudierend 
Is there any progress?

This is just a reminder. Could you release new one?

**Comment by frenetisch-applaudierend** [comment]
Hi @giginet 

Sorry to have kept you waiting, very busy time at the moment here :-)

But it is released now, hope it helps you. Thank you again for your efforts!

**Comment by giginet** [comment]
Thanks! I'll try this next week.

By the way, Could you enable Travis CI environment for this repo?
https://travis-ci.org/konoma/fps-counter

**Pull request merged**
